# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=loopcode_b0d1809cb5
ROOST_METHOD_SIG_HASH=loopcode_9804043493


Scenario 1: Validating loopcode with outer loop and no hole
Details:
  TestName: test_loopcode_no_holes
  Description: This test is intended to verify if the loopcode function correctly returns string representation with outer loop size only when there is no hole.
Execution:
  Arrange: Initialize the class with outer loop data and no hole data.
  Act: Call the loopcode function on the initialized object.
  Assert: Check if the returned string is as expected - a string showing size of outer loop without any hole information.
Validation:
  This test is important to ensure the function handles scenarios without any holes correctly and in line with the business requirements.

Scenario 2: Validating loopcode with multiple holes
Details:
  TestName: test_loopcode_multiple_holes
  Description: This test is intended to verify if loopcode function correctly returns a string representation with outer loop size and sizes of the holes when there are multiple holes.
Execution:
  Arrange: Initialize the class with outer loop data and multiple hole data.
  Act: Call the loopcode function on the initialized object.
  Assert: Check if the returned string is as expected - a string showing size of outer loop and sizes of all holes.
Validation:
  This test validates the function's effectiveness in handling multiple holes, ensuring the function adherently serves diverse business requirements.

Scenario 3: Validating loopcode with single hole
Details:
  TestName: test_loopcode_single_hole
  Description: This test is intended to verify if loopcode accurately returns string representation that contains the size of the outer loop as well as the size of a single hole.
Execution:
  Arrange: Initialize the class with outer loop data and single hole data.
  Act: Call the loopcode function on the initialized object.
  Assert: Check if the returned string is as expected - a string showing size of outer loop and size of the hole.
Validation:
  This test checks the function's ability to handle scenarios with a single hole, cross-verified in compliance with the business needs.

Scenario 4: Validating loopcode with an outer loop containing single point
Details:
  TestName: test_loopcode_single_point_holes
  Description: Assure that a ValueError is raised when an outer loop with less than three points (e.g. one point) is passed.
Execution:
  Arrange: Initialize the class with outer loop data containing a single point and any number of holes.
  Act: A raise condition on calling function loopcode.
  Assert: Check if a ValueError was raised during function execution.
Validation:
  Since it's stated in business logic that loops need at least 3 points, this test will provide verification in line with such circumstances, thereby maintaining data integrity and function robustness.
  
Scenario 5: Validating loopcode when 3D points are given 
Details:
  TestName: test_loopcode_3D_points
  Description: To verify whether a ValueError is thrown when a 3D point is passed.
Execution:
  Arrange: Initialize the class with outer loop data containing a 3D point and respective holes.
  Act: A raise condition on calling function loopcode.
  Assert: Check if ValueError is raised as function encounters 3D points.
Validation:
  It's explicitly mentioned that LatLngPoly only accepts 2D points making this test relevant to address situations when points are not 2D, and thus maintaining function's business logic.

"""

# ********RoostGPT********
import pytest
from _h3shape import LatLngPoly

class Test_LatLngPolyLoopcode:
    
    @pytest.mark.regression
    def test_loopcode_no_holes(self):
        # Arrange
        outer = [(1,2), (3,2), (4,1)] # Any sample outer loop with three or more points
        lat_lng_poly = LatLngPoly(outer)

        # Act
        result = lat_lng_poly.loopcode()

        # Assert
        assert result == '[3]'

    @pytest.mark.regression
    def test_loopcode_multiple_holes(self):
        # Arrange
        outer = [(1,2), (3,2), (4,1)]
        hole1 = [(4,2), (3,2), (4,3)]
        hole2 = [(5,6), (7,5), (8,4)]
        lat_lng_poly = LatLngPoly(outer, hole1, hole2)

        # Act
        result = lat_lng_poly.loopcode()

        # Assert
        assert result == '[3/(3, 3)]'

    @pytest.mark.regression
    def test_loopcode_single_hole(self):
        # Arrange
        outer = [(1,2), (3,2), (4,1)]
        hole1 = [(4,2), (3,2), (4,3)]
        lat_lng_poly = LatLngPoly(outer, hole1)

        # Act
        result = lat_lng_poly.loopcode()

        # Assert
        assert result == '[3/(3,)]'

    @pytest.mark.negative
    def test_loopcode_single_point_loops(self):
        # Arrange
        outer = [(1, 2)]
        hole1 = [(4, 2), (3, 2), (4, 3)]
        hole2 = [(5, 6), (7, 5), (8, 4)]

        # Act
        with pytest.raises(ValueError) as exc_info:
            LatLngPoly(outer, hole1, hole2)

        # Assert
        assert "Non-empty LatLngPoly loops need at least 3 points" in str(exc_info.value)

    @pytest.mark.negative
    def test_loopcode_3D_points(self):
        # Arrange
        outer = [(1, 2, 3), (3, 4, 5), (4, 5, 6)]
        hole1 = [(4, 2), (3, 2), (4, 3)]
        hole2 = [(5, 6), (7, 5), (8, 4)]

        # Act
        with pytest.raises(ValueError) as exc_info:
            LatLngPoly(outer, hole1, hole2)

        # Assert
        assert "LatLngPoly only accepts 2D points: lat/lng" in str(exc_info.value)
