# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test pythonHTest4 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=__init___dd120ed9af
ROOST_METHOD_SIG_HASH=__init___b2c5ddb5aa


```
Scenario 1: Test for minimum number of points in a loop
Details:
  TestName: test_minimum_points_in_loop
  Description: This test is intended to verify that the function raises a ValueError when a loop has less than 3 points.
Execution:
  Arrange: Initialize a loop with less than 3 points.
  Act: Invoke the __init__ function with the initialized loop.
  Assert: Check if a ValueError is raised with the message 'Non-empty LatLngPoly loops need at least 3 points.'
Validation:
  This test is important to ensure that the function correctly enforces the business rule that a loop must have at least 3 points. This is a fundamental requirement for the formation of a polygon.

Scenario 2: Test for 2D points in a loop
Details:
  TestName: test_2d_points_in_loop
  Description: This test is intended to verify that the function raises a ValueError when a loop contains points that are not 2D.
Execution:
  Arrange: Initialize a loop with points that are not 2D.
  Act: Invoke the __init__ function with the initialized loop.
  Assert: Check if a ValueError is raised with the message 'LatLngPoly only accepts 2D points: lat/lng.'
Validation:
  This test is important to ensure that the function correctly enforces the business rule that a loop can only contain 2D points. This is crucial for the correct representation of a polygon in a 2D space.

Scenario 3: Test for correct assignment of outer and holes
Details:
  TestName: test_outer_and_holes_assignment
  Description: This test is intended to verify that the function correctly assigns the outer and holes attributes.
Execution:
  Arrange: Initialize an outer loop and one or more hole loops.
  Act: Invoke the __init__ function with the initialized loops.
  Assert: Check if the outer and holes attributes of the object are correctly assigned.
Validation:
  This test is important to ensure that the function correctly assigns the outer and holes attributes. This is crucial for the correct representation of a polygon with holes.

Scenario 4: Test for correct handling of empty polygons
Details:
  TestName: test_empty_polygons
  Description: This test is intended to verify that the function correctly handles empty polygons.
Execution:
  Arrange: Initialize an empty outer loop.
  Act: Invoke the __init__ function with the initialized loop.
  Assert: Check if the outer attribute of the object is an empty tuple.
Validation:
  This test is important to ensure that the function correctly handles empty polygons. This is crucial for the correct representation of an empty polygon.
```
"""

# ********RoostGPT********
import pytest
from _h3shape import LatLngPoly

class Test_LatLngPolyInit:

    def test_minimum_points_in_loop(self):
        with pytest.raises(ValueError, match='Non-empty LatLngPoly loops need at least 3 points.'):
            LatLngPoly([(1, 2)])

    def test_2d_points_in_loop(self):
        with pytest.raises(ValueError, match='LatLngPoly only accepts 2D points: lat/lng.'):
            LatLngPoly([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

    def test_outer_and_holes_assignment(self):
        outer = [(1, 2), (3, 4), (5, 6)]
        hole1 = [(7, 8), (9, 10), (11, 12)]
        hole2 = [(13, 14), (15, 16), (17, 18)]
        poly = LatLngPoly(outer, hole1, hole2)
        assert poly.outer == tuple(outer[:-1])
        assert poly.holes == (tuple(hole1[:-1]), tuple(hole2[:-1]))

    def test_empty_polygons(self):
        poly = LatLngPoly([])
        assert poly.outer == ()
        assert poly.holes == ()
