# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=__init___dd120ed9af
ROOST_METHOD_SIG_HASH=__init___b2c5ddb5aa


Scenario 1: Validate input with less than 3 coordinates
Details:
  TestName: test_coordinates_less_than_three
  Description: This test validates if the function raises an error when a LatLngPoly loop is provided with less than 3 points.
Execution:
  Arrange: Initialize `outer` with a list containing less than three coordinates.
  Act: Call `__init__` function with `outer`.
  Assert: Validate if value error is raised with correct error message.
Validation: 
  The function is expected to only accept LatLngPoly loops with at least 3 coordinates. This test ensures that this condition is correctly implemented.

Scenario 2: Validate input with 3D coordinates
Details:
  TestName: test_three_dimensional_coordinates
  Description: This test validates if the function raises an error when 3D points are provided as input.
Execution:
  Arrange: Initialize `outer` with a list containing three dimensional coordinates.
  Act: Call `__init__` function with `outer`.
  Assert: Validate if value error is raised with correct error message.
Validation: 
  The function is expected to only accept 2D points. This test ensures that the method correctly handles the case where points with more than 2 coordinates are provided.

Scenario 3: Verify successful object initialization with valid inputs
Details:
  TestName: test_successful_initialization
  Description: This test validates if the object is successfully initialized when valid inputs are provided.
Execution:
  Arrange: Initialize `outer` with three two-dimensional coordinates.
  Act: Call `__init__` function with `outer` and optionally `holes` if present.
  Assert: Validate if `outer` and `holes` are correctly initialized.
Validation: 
  The basic functionality of the provided method __init__ is to initialize the LatLngPoly object with provided parameters. This test ensures that this function works as intended when provided with valid inputs.

Scenario 4: Validate functioning of 'holes' arguments creation
Details:
  TestName: test_holes_creation
  Description: This test validates if the 'holes' argument is correctly created when it's provided as input.
Execution:
  Arrange: Initialize `outer` and `holes` with respective sets of two-dimensional coordinates.
  Act: Call `__init__` function with `outer` and `holes`.
  Assert: Validate if 'holes' are correctly initialized and stored.
Validation: 
  The functionality of the 'holes' argument is to store the coordinates of the "holes" within the polygon created by `outer`. This test will make sure that this functionality is correctly implemented.
"""

# ********RoostGPT********
import pytest
from _h3shape import LatLngPoly

class Test_LatLngPolyInit:

    @pytest.mark.negative
    def test_coordinates_less_than_three(self):
        with pytest.raises(ValueError, match='Non-empty LatLngPoly loops need at least 3 points.'):
            LatLngPoly([(0, 0)])

    @pytest.mark.negative
    def test_three_dimensional_coordinates(self):
        with pytest.raises(ValueError, match='LatLngPoly only accepts 2D points: lat/lng.'):
            LatLngPoly([(0, 0, 0), (1, 1, 1), (2, 2, 2)])

    @pytest.mark.positive
    def test_successful_initialization(self):
        obj = LatLngPoly([(0, 0), (1, 1), (2, 2)])
        assert obj.outer == ((0, 0), (1, 1), (2, 2), (0, 0))
        assert obj.holes == ()

    @pytest.mark.positive
    def test_holes_creation(self):
        obj = LatLngPoly([(0, 0), (1, 1), (2, 2)], [(3, 3), (4, 4), (5, 5)])
        assert obj.outer == ((0, 0), (1, 1), (2, 2), (0, 0))
        assert obj.holes == (((3, 3), (4, 4), (5, 5), (3, 3)),)
