# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=is_res_class_III_6c8eff971b
ROOST_METHOD_SIG_HASH=is_res_class_III_54a1d5ff67


Scenario 1: Test with a Class II cell 
Details:
  TestName: test_is_res_class_III_with_class_II_cell
  Description: This test will verify the correct behavior of the function is_res_class_III when it is invoked with a cell that has "Class II" orientation.
Execution:
  Arrange: Initialize a H3Cell with a resolution equal to an even number within the given range(0 to 14).
  Act: Invoke the function is_res_class_III with the prepared H3Cell as a parameter.
  Assert: Verify that the function returns False.
Validation:
  This test is important because, according to the business rules implemented by the function, "Class II" cells should have even-numbered resolutions, and the function should therefore return False in this situation.

Scenario 2: Test with a Class III cell
Details:
  TestName: test_is_res_class_III_with_class_III_cell
  Description: This test will verify the correct behavior of the function is_res_class_III when it is invoked with a cell that has "Class III" orientation.
Execution:
  Arrange: Initialize a H3Cell with a resolution equal to an odd number within the given range(1 to 15).
  Act: Invoke the function is_res_class_III with the prepared H3Cell as a parameter.
  Assert: Verify that the function returns True.
Validation:
  This test is important because, according to the business rules implemented by the function, "Class III" cells should have odd-numbered resolutions, and the function should therefore return True in this situation.

Scenario 3: Test with an outlier cell
Details:
  TestName: test_is_res_class_III_with_outlier_cell
  Description: This test will verify the behavior of the function is_res_class_III when it is invoked with a cell with resolution out of range(0 to 15).
Execution:
  Arrange: Initialize a H3Cell with a resolution out of range.
  Act: Invoke the function is_res_class_III with the prepared H3Cell as a parameter.
  Assert: Verify the function handles the situation appropriately (e.g., by throwing a relevant exception, returning None, etc.)
Validation:
  This test is important because it ensures that the function can handle outlier cases gracefully, either by rejecting them with an appropriate error message or by returning a sensible default result.

"""

# ********RoostGPT********
import pytest
from typing import Literal
from _h3shape import H3Shape, LatLngPoly, LatLngMultiPoly, geo_to_h3shape, h3shape_to_geo
from _convert import _in_scalar, _out_scalar, _in_collection, _out_collection
from _version import __version__
from __init__ import is_res_class_III


class Test_InitIsResClassIii:

    def test_is_res_class_III_with_class_II_cell(self):
        # Arrange
        h = H3Shape(resolution=2)  # Class II cell

        # Act
        result = is_res_class_III(h)

        # Assert
        assert result == False

    def test_is_res_class_III_with_class_III_cell(self):
        # Arrange
        h = H3Shape(resolution=3)  # Class III cell

        # Act
        result = is_res_class_III(h)

        # Assert
        assert result == True

    def test_is_res_class_III_with_outlier_cell(self):
        # Arrange
        h = H3Shape(resolution=16)  # Outlier cell

        # Act
        with pytest.raises(Exception):  # Change to the specific exception expected
            is_res_class_III(h)
