# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=polygon_to_cells_experimental_f2635be5c8
ROOST_METHOD_SIG_HASH=polygon_to_cells_experimental_d96a11a6c4


```
Scenario 1: Testing correct operation of 'center' contain parameter
Details:
  TestName: test_polygon_to_cells_experimental_center_containment
  Description: This test aims to verify that when the 'center' parameter is used, cells are generated where their center falls within the specified shape.
Execution:
  Arrange: Create a simple H3Shape object and define a resolution for the test.
  Act: Invoke the function with 'center' as the contain parameter.
  Assert: Verify that the cells returned by the function only contain their center within the specified shape.
Validation:
  This test is critical as it validates the primary use case for the contain parameter 'center'. A successful test would verify that the function adheres to requirements and correctly generates cells based on the shape's center.

Scenario 2: Testing the correct operation for 'bbox_overlap' contain parameter
Details:
  TestName: test_polygon_to_cells_experimental_bbox_overlap_containment
  Description: This test verifies that when 'bbox_overlap' contain option is used, cells are generated where their bounding box overlaps with the given shape.
Execution:
  Arrange: Create an H3Shape object and define a resolution for the test.
  Act: Call the function with 'bbox_overlap' as the contain parameter.
  Assert: Confirm that the cells returned by the function have an overlapping bounding box with the given shape.
Validation:
  This test checks the correct operation of the 'bbox_overlap' parameter. This is vital as it confirms whether the function can correctly generate cells based on bounding box overlap.

Scenario 3: Testing the correct operation for the 'full' contain parameter
Details:
  TestName: test_polygon_to_cells_experimental_full_containment
  Description: This test checks that when the 'full' contain option is used, cells which are entirely inside the given shape are generated.
Execution:
  Arrange: Create an H3Shape object along with a defined resolution for the test.
  Act: Call the function with 'full' as the contain parameter.
  Assert: Confirm that the cells returned by the function are all fully contained within the given shape.
Validation:
  This test ensures the function operates as expected for the 'full' contain case. It is important to verify this parameter is correctly implemented, returning only those cells fully contained within the shape.

Scenario 4: Testing the correct operation for the 'overlap' contain parameter
Details: 
  TestName: test_polygon_to_cells_experimental_overlap_containment
  Description: This test aims to verify that when 'overlap' parameter is applied, cells which overlap with the given shape are generated.
Execution:
  Arrange: Build an H3Shape object and a defined resolution.
  Act: Invoke the function with 'overlap' as the contain parameter.
  Assert: Confirm the cells returned by the function are overlapping with the original H3Shape.
Validation:
  This test is vital in validating the correct operation of the 'overlap' selection. It is critical to confirm that cells which overlap with the original shape are correctly returned by the function.
```

These scenarios intended to test the h3shape_to_cells_experimental function mainly focusing on different 'contain' parameters. Suggestions about specific data ranges and variations should be determined while crafting the test code, considering performance and edge cases.
"""

# ********RoostGPT********
import pytest
from typing import Literal
from _h3shape import H3Shape, LatLngPoly, LatLngMultiPoly, geo_to_h3shape, h3shape_to_geo
from _convert import _in_scalar, _out_scalar, _in_collection, _out_collection
from _version import __version__
from __init__ import polygon_to_cells_experimental  # assuming the function defined in __init__.py 

class Test_InitPolygonToCellsExperimental:
    
    def test_polygon_to_cells_experimental_center_containment(self):
        test_shape = H3Shape()  # create your test shape
        test_res = 10  # Define your resolution

        result_cells = polygon_to_cells_experimental(test_shape, test_res, contain = 'center')

        for cell in result_cells:
            # Verify that the cell's center is contained within the original shape
            # As this is a mockup, the actual check with cell's center and test_shape will depend on the specific implementation of these classes
            assert test_shape.contains(cell.center)
    
    def test_polygon_to_cells_experimental_bbox_overlap_containment(self):
        test_shape = H3Shape()  # create your test shape
        test_res = 10  # Define your resolution

        result_cells = polygon_to_cells_experimental(test_shape, test_res, contain = 'bbox_overlap')

        for cell in result_cells:
            # Verify that the cell's bounding box overlaps with the original shape
            # Actual overlap check will depend on the specific implementation of these classes
            assert test_shape.overlaps_with(cell.bbox)
    
    def test_polygon_to_cells_experimental_full_containment(self):
        test_shape = H3Shape()  # create your test shape
        test_res = 10  # Define your resolution

        result_cells = polygon_to_cells_experimental(test_shape, test_res, contain = 'full')

        for cell in result_cells:
            # Verify that the cell is fully contained within the original shape
            # Actual containment check will depend on the specific implementation of these classes 
            assert test_shape.fully_contains(cell)
        
    def test_polygon_to_cells_experimental_overlap_containment(self):
        test_shape = H3Shape()  # create your test shape
        test_res = 10  # Define your resolution

        result_cells = polygon_to_cells_experimental(test_shape, test_res, contain = 'overlap')

        for cell in result_cells:
            # Verify that the cell overlaps with the original shape
            # Actual overlap check will depend on the specific implementation of these classes 
            assert test_shape.overlaps_with(cell)
