# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=h3shape_to_cells_56068aa9cf
ROOST_METHOD_SIG_HASH=h3shape_to_cells_4503e60bbc


```
Scenario 1: Successful conversion of LatLngPoly to H3 cells
Details:
  TestName: test_successful_conversion_latlngpoly
  Description: This test verifies that the function successfully converts a LatLngPoly object into H3 cells.
Execution:
  Arrange: Create a LatLngPoly object that encompasses a known set of H3 cells at a given resolution level. 
  Act: Pass the LatLngPoly object and the resolution level to h3shape_to_cells.
  Assert: The function should return a list of H3 cells that are both correct and complete.
Validation:
  The functionality of the LatLngPoly-to-H3 cell conversion is at the core of this function. Therefore, its success is critically linked to the correctness of the function's logic and its ability to fulfill its business purposes.
  
Scenario 2: Successful conversion of LatLngMultiPoly to H3 cells
Details:
  TestName: test_successful_conversion_latlngmultipoly
  Description: This test verifies that the function successfully converts a LatLngMultiPoly object into H3 cells.
Execution:
  Arrange: Create a LatLngMultiPoly object that encompasses a known set of H3 cells at a given resolution level.
  Act: Pass the LatLngMultiPoly object and the resolution level to h3shape_to_cells.
  Assert: The function should return a list of H3 cells that are both correct and complete.
Validation:
  The functionality of the LatLngMultiPoly-to-H3 cell conversion is another major part of this function; therefore, its success is critically linked to the correctness of the function's logic and its ability to fulfill its business purposes.

Scenario 3: Conversion of unrecognized H3Shape
Details:
  TestName: test_unrecognized_h3shape_conversion
  Description: This test verifies that the function correctly raises a ValueError for unrecognized H3Shape types.
Execution:
  Arrange: Create an object of a class that is not recognized as a correct H3Shape (i.e., not LatLngPoly or LatLngMultiPoly).
  Act: Pass the unknown object along with a resolution level to h3shape_to_cells.
  Assert: The function should raise a ValueError indicating an unrecognized H3Shape.
Validation:
  This scenario tests the function's error handling logic, ensuring that it properly rejects input of an incorrect type and provides clear feedback about the error.

Scenario 4: Conversion of unrecognized type
Details:
   TestName: test_unrecognized_type_conversion
   Description: This scenario is intended to test whether or not a ValueError is thrown when the function h3shape_to_cells receives an object type it does not recognize.
Execution:
   Arrange: Pass an object that does not belong to any of the recognized classes (LatLngPoly, LatLngMultiPoly).
   Act: Attempt to execute h3shape_to_cells with this object and any resolution.
   Assert: The function should raise a ValueError explaining that it received an unrecognized type.
Validation:
   This scenario validates the function's integrity in handling unexpected object types, and the feedback provided allows users to correct the data type-errors.
"""

# ********RoostGPT********
import pytest
from typing import Literal
from _h3shape import H3Shape, LatLngPoly, LatLngMultiPoly, geo_to_h3shape, h3shape_to_geo
from _convert import _in_scalar, _out_scalar, _in_collection, _out_collection
from _version import __version__

class Test_InitH3ShapeToCells:

    def test_successful_conversion_latlngpoly(self):
        # Arrange
        h3shape = LatLngPoly(
            [(37.68, -122.54), (37.68, -122.34), (37.82, -122.34),
             (37.82, -122.54)]
        )
        resolution = 6
        expected_result = ['862830807ffffff',
                           '862830827ffffff',
                           '86283082fffffff',
                           '862830877ffffff',
                           '862830947ffffff',
                           '862830957ffffff',
                           '86283095fffffff']

        # Act
        result = h3shape_to_cells(h3shape, resolution)

        # Assert
        assert sorted(result) == sorted(expected_result)

    def test_successful_conversion_latlngmultipoly(self):
        # Arrange
        h3shape = LatLngMultiPoly(
            [[(37.68, -122.54), (37.68, -122.34), (37.82, -122.34), (37.82, -122.54)]]
        )
        resolution = 6
        expected_result = ['862830807ffffff',
                           '862830827ffffff',
                           '86283082fffffff',
                           '862830877ffffff',
                           '862830947ffffff',
                           '862830957ffffff',
                           '86283095fffffff']

        # Act
        result = h3shape_to_cells(h3shape, resolution)

        # Assert
        assert sorted(result) == sorted(expected_result)

    def test_unrecognized_h3shape_conversion(self):
        # Arrange
        h3shape = H3Shape()
        resolution = 6

        # Act and Assert
        with pytest.raises(ValueError, match="Unrecognized H3Shape:"):
            h3shape_to_cells(h3shape, resolution)

    def test_unrecognized_type_conversion(self):
        # Arrange
        h3shape = object()
        resolution = 6

        # Act and Assert
        with pytest.raises(ValueError, match="Unrecognized type:"):
            h3shape_to_cells(h3shape, resolution)
