# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=grid_disk_e2ac10514b
ROOST_METHOD_SIG_HASH=grid_disk_3d4ddcc855


Scenario 1: Test grid_disk function with minimum values
Details:
  TestName: test_grid_disk_minimum_values
  Description: This test will verify that the grid_disk function works correctly with the smallest possible grid distance. In this case 'h' will be the minimal possible H3Cell value and k = 1.
Execution:
  Arrange: No significant setup is required beyond ensuring that the testing environment can execute the function.
  Act: Call the grid_disk function, passing the smallest possible H3Cell value as 'h' and 1 as 'k'.
  Assert: Check that the function returns a valid H3Cell collection.
Validation:
  This test is important because it verifies that the function can handle the edge case of the smallest possible input. If it passes, it's an indication that the function and its dependencies are designed correctly. 

Scenario 2: Test grid_disk function with maximum values
Details:
  TestName: test_grid_disk_maximum_values
  Description: This test will verify that the grid_disk function works correctly with the largest possible grid distance. In this case 'h' will be the maximal possible H3Cell value and k will be the largest allowed int.
Execution:
  Arrange: No significant setup is required beyond ensuring that the testing environment can execute the function.
  Act: Call the grid_disk function, passing the largest possible H3Cell value as 'h' and the largest int value as 'k'.
  Assert: Check that the function returns a valid H3Cell collection, likely quite large.
Validation:
  This test is critical because it verifies that the function can handle the edge case of the largest possible input. In addition, it provides insight into the performance of the function with large inputs, which can inform decisions about optimization.

Scenario 3: Test grid_disk function with typical values
Details:
  TestName: test_grid_disk_typical_values
  Description: This test will verify that the grid_disk function works correctly with typical (average) grid distance values. This means testing with an average 'h' and 'k' values.
Execution:
  Arrange: No significant setup is required beyond ensuring that the testing environment can execute the function.
  Act: Call the grid_disk function, passing a typical/average H3Cell value as 'h' and an average 'k' value.
  Assert: Check that the function returns a valid H3Cell collection.
Validation:
  This test verifies the function's basic functionality. If it fails, it may be an indication that there is a fundamental problem with the function design or underlying dependencies.

Scenario 4: Test grid_disk function with Non-H3Cell input 
Details:
  TestName: test_grid_disk_non_H3Cell_input
  Description: This test will verify the behavior of the grid_disk function when input other than H3Cell is passed. Ideally, it should throw an exception or an error.
Execution:
  Arrange: No significant setup is required beyond ensuring that the testing environment can execute the function.
  Act: Call the grid_disk function, passing a type that is not H3Cell as 'h' and an int for 'k'.
  Assert: Check that the function raises an exception or throws an error.
Validation:
  This test is critical as it checks if the function has safeguarded against invalid inputs.

Scenario 5: Test grid_disk function when k is zero
Details:
  TestName: test_grid_disk_k_zero
  Description: This test will verify the behavior of the function when k=0. In theory, the function should return a collection containing just the input 'h' H3Cell.
Execution:
  Arrange: No significant setup is required beyond ensuring that the testing environment can execute the function.
  Act: Call the grid_disk function, passing a valid H3Cell as 'h' and 'k' as zero.
  Assert: Check that the function returns a collection containing only 'h'.
Validation:
  This test verifies the behavior of the function under a boundary condition scenario where k is 0.
"""

# ********RoostGPT********
import pytest
from typing import Literal
from _h3shape import H3Shape, LatLngPoly, LatLngMultiPoly, geo_to_h3shape, h3shape_to_geo
from _convert import _in_scalar, _out_scalar, _in_collection, _out_collection
from _version import __version__

# Import the function to test
from __init__ import grid_disk

# Define the test class
class Test_InitGridDisk:

    def test_grid_disk_minimum_values(self):
        # Arrange
        h_min = geo_to_h3shape((0, 0))  # Smallest H3Cell
        k = 1

        # Act
        result = grid_disk(h_min, k)

        # Assert
        assert isinstance(result, dict)
        assert all([isinstance(v, H3Shape) for v in result.values()])

    def test_grid_disk_maximum_values(self):
        # Arrange
        h_max = geo_to_h3shape((90, 180))  # Largest H3Cell
        k = int(1e9)  # Largest allowed integer

        # Act
        result = grid_disk(h_max, k)

        # Assert
        assert isinstance(result, dict)
        assert all([isinstance(v, H3Shape) for v in result.values()])

    def test_grid_disk_typical_values(self):
        # Arrange
        h_typical = geo_to_h3shape((45, 90))  # Typical H3Cell
        k = 100  # Typical k

        # Act
        result = grid_disk(h_typical, k)

        # Assert
        assert isinstance(result, dict)
        assert all([isinstance(v, H3Shape) for v in result.values()])

    def test_grid_disk_non_H3Cell_input(self):
        # Arrange
        h_invalid = "not a H3Cell"  # Invalid H3Cell
        k = 1

        # Act and Assert
        with pytest.raises(ValueError):
            grid_disk(h_invalid, k)

    def test_grid_disk_k_zero(self):
        # Arrange
        h_valid = geo_to_h3shape((45, 90))  # Valid H3Cell
        k = 0

        # Act
        result = grid_disk(h_valid, k)

        # Assert
        assert isinstance(result, dict)
        assert len(result) == 1
        assert all([isinstance(v, H3Shape) for v in result.values()])
