# ********RoostGPT********
"""
Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test pythonHTest4 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=get_resolution_a900bdded2
ROOST_METHOD_SIG_HASH=get_resolution_4dd011a16e


Scenario 1: Confirm functionality with valid H3 cell
Details:
  TestName: test_resolution_with_valid_cell
  Description: This test is designed to verify the function's ability to correctly return the resolution of a valid H3 cell.
Execution:
  Arrange: Prepare a valid H3 cell as the input parameter.
  Act: Call the function get_resolution with the H3 cell as a parameter.
  Assert: Check if the returned value is the correct resolution for the given cell.
Validation:
  This test is crucial to confirm that the function behaves as expected under ideal conditions. It ensures the H3 cell is converted to scalar and the function correctly returns resolved scalar values.

Scenario 2: Assert functionality with edge case of lowest possible H3 cell value
Details:
  TestName: test_resolution_with_lowest_possible_cell
  Description: This test is meant to check how the function behaves with the lowest possible value of H3 cell.
Execution:
  Arrange: Use the lowest possible cell value as input.
  Act: Run the function get_resolution with the low cell value.
  Assert: Expect the returned value to match the correct resolution of the worst cell case.
Validation:
  This test is important for ensuring that the function can handle edge cases. This ensures robustness and reliability of the function.

Scenario 3: Testing with the highest possible H3 cell value
Details:
  TestName: test_resolution_with_highest_possible_cell
  Description: This test examines the behavior of the function with the highest possible H3 cell value as a parameter. 
Execution:
  Arrange: Produce the highest possible H3 cell as the input parameter.
  Act: Invoke the function get_resolution with the high value H3 cell.
  Assert: Verify that the return value should match the correct resolution for the highest case H3 cell.
Validation:
  This test is essential for ensuring the function's ability to correctly handle its maximum possible input range. It's crucial for the reliability of the function in all scenarios.

Scenario 4: Functionality with edge case of negative H3 cell value
Details:
  TestName: test_resolution_with_negative_cell
  Description: This test is designed to check how the function will react when given an invalid H3 cell (a negative value).
Execution:
  Arrange: Use a negative value as the H3 cell.
  Act: Run the function get_resolution with the negative H3 cell.
  Assert: The expected outcome will depend on the function's specifications. It may return a default value, an error message, or throw an exception.
Validation:
  This test ensures the function's robustness in handling edge cases, which is important for maintaining the stability of the broader system.
"""

# ********RoostGPT********
import pytest
from typing import Literal
from _h3shape import H3Shape, LatLngPoly, LatLngMultiPoly, geo_to_h3shape, h3shape_to_geo
from _convert import _in_scalar, _out_scalar, _in_collection, _out_collection
from _version import __version__
from __init__ import get_resolution


class Test_InitGetResolution:

    @pytest.mark.regression
    def test_resolution_with_valid_cell(self):
        valid_cell = H3Shape(3, 3, "face", 5)
        h = _in_scalar(valid_cell)
        assert get_resolution(h) == _cy.get_resolution(h)

    @pytest.mark.regression
    def test_resolution_with_lowest_possible_cell(self):
        lowest_cell = H3Shape(0, 0, "face", 0)
        h = _in_scalar(lowest_cell)
        assert get_resolution(h) == _cy.get_resolution(h)

    @pytest.mark.regression
    def test_resolution_with_highest_possible_cell(self):
        highest_cell = H3Shape(4, 4, "face", 10)
        h = _in_scalar(highest_cell)
        assert get_resolution(h) == _cy.get_resolution(h)

    @pytest.mark.negative
    def test_resolution_with_negative_cell(self):
        negative_cell = H3Shape(-1, -1, "face", -1)
        h = _in_scalar(negative_cell)
        with pytest.raises(Exception):
            get_resolution(h)
